### ISSUE TITLE
rename equil_torsion_angle everywhere

### ISSUE THREAD

**Issue by cwalker7** [shirtsgroup/cg_openmm#104]
The parameter we have been calling 'equil_torsion_angle' is actually the phase offset of periodic torsions. http://docs.openmm.org/development/api-python/generated/simtk.openmm.openmm.PeriodicTorsionForce.html

It seems misleading to keep that variable name, so we should rename it something else like 'torsion_phase_offset'.

This is why we were seeing a torsion peak at 180-equil_torsion_angle for periodicity=1. (see https://github.com/shirtsgroup/analyze_foldamers/issues/12)

**Comment by mrshirts** [comment]
Yeah, go ahead and make the change (just make sure that examples are updated as well).

**Comment by cwalker7** [comment]
Ok I changed this here: #102
