### ISSUE TITLE
exchange frequency not passed to run_replica_exchange in example

### ISSUE THREAD

**Issue by cwalker7** [shirtsgroup/cg_openmm#32]
Looks like the replica exchange example uses the default 'exchange attempts', which is the total number of exchange attempts throughout the whole simulation. The default is total time steps / 1000, or 10 if < 10000 steps. The pickle data storage command uses 'exchange frequency' which we took as the number of time steps between exchange attempts. Seems like we can simplify things by passing only frequency into run_replica_exchange? And should we make this a mandatory argument for run_replica_exchange?

**Comment by mrshirts** [comment]
Definitely should be easier to set this, especially since flexibility in this it is likely to be key in improving scaling to more nodes.
