### ISSUE TITLE
Torsions as sums of periodic terms

### ISSUE THREAD

**Issue by mrshirts** [shirtsgroup/cg_openmm#53]
It appears that currently, torsions only have one periodic term, rather than being a sum of multiple terms.  This should be addressed at some point.  

Perhaps this should be implemented with torsions parameters as a list, rather than a single entry.

**Comment by cwalker7** [comment]
My thought on this is to use a custom torsion force, where the user the can type in any functional form they want (with some limitations), along with the per-torsion parameter values. We could add in a few preset options later on to make it easier, such as sum of 2 or 3 periodic torsions.
http://docs.openmm.org/latest/api-python/generated/simtk.openmm.openmm.CustomTorsionForce.html#simtk.openmm.openmm.CustomTorsionForce

We will need to update the code in cgmodel and cg_build to allow for this. I can take a shot at it.

**Comment by mrshirts** [comment]
OpenMM does support sums of torsions as http://docs.openmm.org/development/api-python/generated/simtk.openmm.openmm.PeriodicTorsionForce.html.  So it may be easier to go with the already defined option for now.  Eventually, we will want custom functional forms. Thoughts?

**Comment by cwalker7** [comment]
Do you mean adding multiple PeriodicTorsionForce to the same group of atoms? Otherwise I'm not sure how this is any different than what we are currently using.

**Comment by mrshirts** [comment]
> Do you mean adding multiple PeriodicTorsionForce to the same group of atoms? Otherwise I'm not sure how this is any different than what we are currently using.

I guess that is essentially the same - it would just need the interface checked so that multiple terms could indeed be added. 

Alternatively, there is this, which is equivalent to a sum of periodic terms.
http://docs.openmm.org/7.1.0/api-python/generated/simtk.openmm.openmm.RBTorsionForce.html

**Comment by cwalker7** [comment]
We've implemented the sums of periodic torsions with input parameters as a list - I'll close this now.
