### ISSUE TITLE
Heat capacity calculation running out of memory

### ISSUE THREAD

**Issue by cwalker7** [shirtsgroup/cg_openmm#79]
When running the heat capacity calculation for large trajectories (for example 50,000 frames for each of 36 replicas, so not really excessively huge), the calculation crashes due to running out of memory. I believe my workstation has 32GB of RAM, so this is definitely as issue.

We should look for where we could cut down on the memory usage. Another solution could be do break it up into chunks of the trajectory, and do block-averaging. Might also be useful for checking the convergence of heat capacity.

**Comment by mrshirts** [comment]
Is time series analysis being run? We can make sure we have uncorrelated data.  If still too big, can thin the data some more.

**Comment by cwalker7** [comment]
To follow up on the conversation yesterday, I hadn't been using timeseries analysis here, but am now working on using the subsampleCorrelatedData to refine the data. I am testing it out in process_replica_exchange running this on 'state_energies' (the same energy array we are using for physical validation). In the heat capacity code, I believe we would use it on the reduced 'unsampled_state_energies.'

Discarding the initial equilibration period is straightforward, but the subsampleCorrelatedData function gives different lengths of indices for each state (irregular spacing). There is an option 'conservative=True' which gives equal spacing. I guess the best solution is to find the most conservative spacing from all replicas?

**Comment by mrshirts** [comment]
> I guess the best solution is to find the most conservative spacing from all replicas?

Yes, I think so.

**Comment by cwalker7** [comment]
Don't seem to be having this issue anymore now that I am only using the uncorrelated data, closing this now.
