### ISSUE TITLE
Add tools for saving a molecular snapshot

### ISSUE THREAD

**Issue by cwalker7** [shirtsgroup/cg_openmm#95]
It would be useful to be able to render and save a molecular snapshot from the command line, without having to open VMD or some other GUI to see what structures look like a different states. 

For example, we might want to view in one pdf file what representative structures of all states look like (determined from rmsd similarity matrix at each state).

I'm thinking something like Ovito might work https://www.ovito.org/.

**Comment by cwalker7** [comment]
Been looking into this a lot recently - it is possible to open VMD in text mode (no display window), and render a molecule using Tachyon from the command line. I tried it out on Mt. Antero and it works. It should also work on HPC platforms:

https://www.ks.uiuc.edu/Training/Tutorials/vmd/tutorial-html/node8.html

I'll put together a script that cycles through and renders a list of specified pdb files. The default view angle is probably good enough for now if we just want to see what secondary structure the foldamer has.

**Comment by mrshirts** [comment]
Glad that worked!

**Comment by cwalker7** [comment]
Addressed this in analyze_foldamers here: https://github.com/shirtsgroup/analyze_foldamers/pull/24
