### ISSUE TITLE
process replica exchange running out of memory

### ISSUE THREAD

**Issue by cwalker7** [shirtsgroup/cg_openmm#99]
On CU Summit (2 tasks per node on 1 shas node), process replica exchange seems to be running out of memory during the make_state_dcd_files step (the replica dcd files are created, and then it fails):

```
make_state_dcd_files(
    cgmodel.topology,
    replica_positions,
    replica_states,
    timestep=5*unit.femtosecond,
    time_interval=200,
    output_dir=output_directory
)
```

We get an error like this:

`slurmstepd: error:   Detected 1 oom-kill event(s) in step 6227009.batch cgroup. Some of your processes may have been killed by the cgroup out-of-memory handler.`

According to the CURC website, the Haswell nodes have 4.84 GB memory / core.
It worked fine for 36 replica, 48-particle 20ns trajectories (36 x 20,000 frames), but not 50ns trajectories (36 x 50,000 frames)

**Comment by mrshirts** [comment]
This might need to be a question for OpenMM.  I'm not quite sure what the main reason could be.

Given that it's trajectory length dependent, maybe it would be solved with fewer frames kept?   Is it set up so one can vary the number of frames but keep the number of exchanges fixed?

**Comment by cwalker7** [comment]
Yeah I think the issue is that there are more huge arrays used in the state trajectory function vs. the replica trajectory (both replica positions and state positions, which are 4D arrays). We could look at that Yank .nc reader code again to see how it could be improved. This is our code now:

```
    file_list = []
    state_positions = np.zeros_like(replica_positions)
    
    for replica_index in range(len(replica_positions)):
        for frame in range(len(replica_state_indices[0,:])):
            # For each frame, assign replica_positions to state positions
            state_positions[replica_state_indices[replica_index,frame],frame,:,:]=replica_positions[replica_index][frame]
        
    for state_index in range(len(replica_positions)):
        state_trajectory = state_positions[state_index][frame_begin::stride]
    
        file_name = os.path.join(output_dir, "state_" + str(state_index + 1) + ".dcd")
        file = open(file_name, "wb")
        dcd_file = DCDFile(file, topology, timestep, firstStep=frame_begin,interval=time_interval)
        
        #***Note: if we have different masses for particle types, need to update this
        if center==True:
            center_x = np.mean(state_trajectory[0,:,0])
            center_y = np.mean(state_trajectory[0,:,1])
            center_z = np.mean(state_trajectory[0,:,2])
        
        for positions in state_trajectory[::stride]:
            if center==True:
                positions[:,0] += (center_x - np.mean(positions[:,0]))
                positions[:,1] += (center_y - np.mean(positions[:,1]))
                positions[:,2] += (center_z - np.mean(positions[:,2]))
                
            # Add the units consistent with replica_energies
            positions *= replica_positions.unit
            DCDFile.writeModel(dcd_file, positions)
        file.close()
        file_list.append(file_name)
```

Doing one state at a time and clearing state_positions between each state would definitely help. 

>  Is it set up so one can vary the number of frames but keep the number of exchanges fixed?

Right now we are writing a frame after each exchange. We could still thin out the trajectories since the correlation time is usually >5 frames, but it would be nice to keep the entire dataset until we're done with all the analysis.

**Comment by cwalker7** [comment]
This issue seems to be fixed with the new process_replica_exchange and trajectory writing functions. It's working fine with 50ns (36 x 50,000 frame) trajectories.
